import { useState } from "react";
import { Button, Input, Select, Textarea } from "../../../components/ui";
import type { PaymentMode, PaymentStatus, PharmacyBillItem } from "../types";
import { PharmacyBillPreview } from "./PharmacyBillPreview";

export function PharmacyBillBuilder() {
  const [mode, setMode] = useState<PaymentMode>("upi"); const [status, setStatus] = useState<PaymentStatus>("paid");
  const [items, setItems] = useState<PharmacyBillItem[]>([{ medicineName: "Paracetamol 500mg", quantity: 6, unitPrice: 2.5, discount: 0 }, { medicineName: "ORS Sachet", quantity: 2, unitPrice: 15, discount: 0 }]);
  return <div className="grid gap-5 xl:grid-cols-[1fr_.9fr]"><div className="card p-5"><h2 className="font-bold">Generate Pharmacy Bill</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><Input placeholder="Patient" defaultValue="Neha Iyer" /><Input placeholder="Prescription reference" defaultValue="rx1 / Token A009" /></div><div className="mt-4 space-y-3">{items.map((item, idx) => <div key={idx} className="grid gap-3 rounded-xl border p-3 md:grid-cols-[1fr_90px_120px_120px]"><Input value={item.medicineName} onChange={(e) => setItems(items.map((it, i) => i === idx ? { ...it, medicineName: e.target.value } : it))} /><Input type="number" value={item.quantity} onChange={(e) => setItems(items.map((it, i) => i === idx ? { ...it, quantity: Number(e.target.value) } : it))} /><Input type="number" value={item.unitPrice} onChange={(e) => setItems(items.map((it, i) => i === idx ? { ...it, unitPrice: Number(e.target.value) } : it))} /><Input type="number" value={item.discount} onChange={(e) => setItems(items.map((it, i) => i === idx ? { ...it, discount: Number(e.target.value) } : it))} /></div>)}</div><Button className="mt-3" variant="secondary" onClick={() => setItems([...items, { medicineName: "", quantity: 1, unitPrice: 0, discount: 0 }])}>Add extra medicine</Button><div className="mt-4 grid gap-3 md:grid-cols-2"><Select value={mode} onChange={(e) => setMode(e.target.value as PaymentMode)}><option value="cash">Cash</option><option value="upi">UPI</option><option value="card">Card</option><option value="online_link">Online Link</option></Select><Select value={status} onChange={(e) => setStatus(e.target.value as PaymentStatus)}><option value="paid">Paid</option><option value="pending">Pending</option><option value="partial">Partial</option></Select><Textarea className="md:col-span-2" placeholder="Notes" /></div><div className="mt-4 flex flex-wrap gap-2"><Button>Generate Bill</Button><Button variant="secondary">Print Bill</Button><Button variant="secondary">Send Bill to WhatsApp</Button><Button>Mark as Dispensed</Button></div></div><PharmacyBillPreview items={items} paymentMode={mode} paymentStatus={status} /></div>;
}
