import { BadgeIndianRupee, Building2, CircleOff, FlaskConical } from "lucide-react";
import { PageHeader } from "../../components/common/PageHeader";
import { StatsCard } from "../../components/common/StatsCard";
import { Card } from "../../components/common/Card";
import { StatusPill } from "../../components/common/StatusPill";
const signups=[["Glow Skin Clinic","Mumbai","Growth","Active"],["Aarogya Family Care","Pune","Trial","Trial"],["Pearl Dental Studio","Bengaluru","Starter","Active"],["Wellness First Clinic","Hyderabad","Growth","Pending"]];
export default function SuperAdminDashboard(){
 return <><PageHeader title="Platform overview" description="Monitor clinic growth, subscriptions, and support health."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatsCard label="Total clinics" value="248" detail="+18 this month" icon={Building2}/><StatsCard label="Active clinics" value="219" detail="88.3% active" icon={Building2} tone="blue"/><StatsCard label="Trial clinics" value="21" detail="8 expiring soon" icon={FlaskConical} tone="amber"/><StatsCard label="Expired clinics" value="8" detail="Needs outreach" icon={CircleOff} tone="violet"/><StatsCard label="Monthly recurring revenue" value="₹8.42L" detail="+9.8% MoM" icon={BadgeIndianRupee}/></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_.5fr]"><Card className="overflow-hidden"><div className="p-5"><h2 className="font-bold">Recent clinic signups</h2><p className="text-xs text-slate-500">Newest workspaces on Vernex</p></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Clinic</th><th>City</th><th>Plan</th><th>Status</th></tr></thead><tbody>{signups.map(s=><tr key={s[0]}><td className="font-semibold">{s[0]}</td><td>{s[1]}</td><td>{s[2]}</td><td><StatusPill status={s[3].toLowerCase()}/></td></tr>)}</tbody></table></div></Card><Card className="p-5"><h2 className="font-bold">Support pulse</h2><p className="text-xs text-slate-500">Open platform tickets</p><div className="mt-5 space-y-4">{[["Critical","2","text-rose-600"],["Awaiting reply","7","text-amber-600"],["Resolved today","18","text-emerald-600"]].map(x=><div className="flex items-center justify-between border-b pb-3" key={x[0]}><span className="text-sm text-slate-500">{x[0]}</span><b className={x[2]}>{x[1]}</b></div>)}</div></Card></div></>;
}
