import { appointmentReport, billingStats, doctorPerformanceReport, followUpReport, invoices, patientReport, pendingPayments, pharmacySalesReport, receipts, refunds, revenueReport } from "../modules/billing/mock";
import type { Invoice, PaymentStatus, Refund } from "../modules/billing/types";
export const getBillingStats = () => billingStats;
export const getInvoices = () => invoices;
export const getReceipts = () => receipts;
export const getPendingPayments = () => pendingPayments;
export const getRefunds = () => refunds;
export const createBill = (input: Partial<Invoice>) => ({ ...invoices[0], ...input, id: `INV-${Date.now()}` });
export const updatePaymentStatus = (id: string, status: PaymentStatus) => invoices.map((i) => i.id === id ? { ...i, paymentStatus: status } : i);
export const createRefund = (input: Partial<Refund>) => ({ ...refunds[0], ...input, id: `REF-${Date.now()}` });
export const getRevenueReport = () => revenueReport;
export const getAppointmentReport = () => appointmentReport;
export const getDoctorPerformanceReport = () => doctorPerformanceReport;
export const getPharmacySalesReport = () => pharmacySalesReport;
export const getPatientReport = () => patientReport;
export const getFollowUpReport = () => followUpReport;
