import { CalendarCheck, CircleDollarSign, Clock3, Pill, UserPlus, Users, WalletCards, Waypoints } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { appointments, appointmentMix, doctorRevenue, medicines, payments, revenueTrend } from "../../data/mockData";
import { StatsCard } from "../../components/common/StatsCard";
import { PageHeader } from "../../components/common/PageHeader";
import { Card } from "../../components/common/Card";
import { StatusPill } from "../../components/common/StatusPill";
import { formatCurrency } from "../../utils/formatCurrency";
export default function OwnerDashboard() {
  const stats = [
    ["Today Revenue", "₹47,200", "+12.4% vs yesterday", CircleDollarSign, "teal"], ["Appointments", "38", "31 confirmed", CalendarCheck, "blue"],
    ["Waiting Patients", "6", "Avg. wait 14 min", Clock3, "amber"], ["New Patients", "9", "24% of visits", UserPlus, "violet"],
    ["Repeat Patients", "22", "58% retention", Users, "teal"], ["Pharmacy Sales", "₹12,840", "27 orders", Pill, "blue"],
    ["Pending Payments", "₹6,450", "5 invoices", WalletCards, "amber"], ["Follow-ups Due", "11", "3 high priority", Waypoints, "violet"]
  ] as const;
  return <><PageHeader title="Good morning, Varun" description="Here’s how your clinic is doing today." action={<button className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold text-slate-700">1 Jul 2026</button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, detail, icon, tone]) => <StatsCard key={label} label={label} value={value} detail={detail} icon={icon} tone={tone} />)}</div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.55fr_1fr]">
      <Card className="p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Revenue trend</h2><p className="text-xs text-slate-500">Daily collections this week</p></div><span className="text-sm font-bold text-emerald-600">+18.2%</span></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenueTrend}><defs><linearGradient id="rev" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#13969c" stopOpacity={.25}/><stop offset="95%" stopColor="#13969c" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e9eef1" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:12}} /><YAxis axisLine={false} tickLine={false} tick={{fontSize:11}} tickFormatter={(v) => `${v/1000}k`} /><Tooltip formatter={(v) => formatCurrency(Number(v))} /><Area type="monotone" dataKey="revenue" stroke="#087f8c" strokeWidth={2.5} fill="url(#rev)" /></AreaChart></ResponsiveContainer></div></Card>
      <Card className="p-5"><h2 className="font-bold">Appointment status</h2><p className="text-xs text-slate-500">Today’s patient flow</p><div className="h-52"><ResponsiveContainer><PieChart><Pie data={appointmentMix} dataKey="value" innerRadius={55} outerRadius={80} paddingAngle={3}>{appointmentMix.map((x) => <Cell key={x.name} fill={x.fill} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3">{appointmentMix.map((x) => <div className="flex items-center justify-between text-xs" key={x.name}><span className="flex items-center gap-2 text-slate-500"><i className="size-2 rounded-full" style={{background:x.fill}} />{x.name}</span><b>{x.value}</b></div>)}</div></Card>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2">
      <Card className="overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="font-bold">Today’s appointments</h2><p className="text-xs text-slate-500">Next patients across all doctors</p></div><button className="text-sm font-semibold text-brand-700">View all</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Patient</th><th>Doctor</th><th>Time</th><th>Status</th></tr></thead><tbody>{appointments.map((a) => <tr key={a.id}><td className="font-semibold">{a.patientName}</td><td className="text-slate-500">{a.doctorName}</td><td>{a.time}</td><td><StatusPill status={a.status} /></td></tr>)}</tbody></table></div></Card>
      <Card className="p-5"><h2 className="font-bold">Doctor-wise revenue</h2><p className="text-xs text-slate-500">Collections for the current month</p><div className="mt-4 h-64"><ResponsiveContainer><BarChart data={doctorRevenue} layout="vertical" margin={{left:10}}><CartesianGrid horizontal={false} stroke="#edf1f3" /><XAxis type="number" hide /><YAxis dataKey="name" type="category" width={70} axisLine={false} tickLine={false} tick={{fontSize:11}} /><Tooltip formatter={(v) => formatCurrency(Number(v))}/><Bar dataKey="value" fill="#13969c" radius={[0,8,8,0]} barSize={22}/></BarChart></ResponsiveContainer></div></Card>
      <Card className="overflow-hidden"><div className="p-5"><h2 className="font-bold">Recent payments</h2><p className="text-xs text-slate-500">Latest clinic collections</p></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Patient</th><th>Mode</th><th>Amount</th></tr></thead><tbody>{payments.map((p) => <tr key={p.id}><td className="text-slate-500">{p.id}</td><td className="font-semibold">{p.patientName}</td><td>{p.mode}</td><td className="font-bold">{formatCurrency(p.amount)}</td></tr>)}</tbody></table></div></Card>
      <Card className="overflow-hidden"><div className="p-5"><h2 className="font-bold">Low stock medicines</h2><p className="text-xs text-slate-500">Items below reorder level</p></div>{medicines.map((m) => <div key={m.id} className="flex items-center justify-between border-t px-5 py-4"><div><p className="text-sm font-semibold">{m.name}</p><p className="text-xs text-slate-500">{m.category} · Exp. {m.expiry}</p></div><div className="text-right"><p className="text-sm font-bold text-rose-600">{m.stock} left</p><p className="text-xs text-slate-400">Min {m.reorderLevel}</p></div></div>)}</Card>
    </div>
  </>;
}
