import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button, Input, Select, Textarea } from "../../../components/ui";
import type { PatientBookingInput } from "../types";

const schema = z.object({ fullName: z.string().min(2, "Name required"), phone: z.string().min(10, "Phone required"), age: z.coerce.number().min(0).max(120), gender: z.enum(["female", "male", "other"]), reason: z.string().min(2, "Reason required"), existingPatient: z.boolean().optional(), patientId: z.string().optional(), notes: z.string().optional() });
export function PatientDetailsForm({ defaultValue, onSubmit }: { defaultValue: PatientBookingInput; onSubmit: (input: PatientBookingInput) => void }) {
  const { register, handleSubmit, formState: { errors } } = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema), defaultValues: { ...defaultValue, gender: defaultValue.gender || "female" } });
  return <form onSubmit={handleSubmit((input) => onSubmit({ ...input, existingPatient: Boolean(input.existingPatient) } as PatientBookingInput))} className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Field label="Full name" error={errors.fullName?.message}><Input {...register("fullName")} placeholder="Enter patient name" /></Field><Field label="Phone number" error={errors.phone?.message}><Input {...register("phone")} placeholder="+91 98765 43210" /></Field><Field label="Age" error={errors.age?.message}><Input {...register("age")} type="number" placeholder="Age" /></Field><Field label="Gender" error={errors.gender?.message}><Select {...register("gender")}><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></Select></Field><label className="flex items-center gap-2 rounded-2xl border p-3 text-sm font-semibold md:col-span-2"><input type="checkbox" {...register("existingPatient")} /> Existing patient</label><Input {...register("patientId")} placeholder="Patient ID optional" /><Field label="Reason for visit" error={errors.reason?.message}><Input {...register("reason")} placeholder="Briefly describe concern" /></Field><Textarea className="md:col-span-2" {...register("notes")} placeholder="Notes optional" /></div><Button className="w-full md:w-auto" type="submit">Continue to Confirm</Button></form>;
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="text-xs font-bold text-slate-600">{label}{children}{error && <span className="mt-1 block text-xs text-rose-600">{error}</span>}</label>; }
