import { useMemo, useState } from "react";
import { ReceiptIndianRupee } from "lucide-react";
import { Button, Card, Input, PageHeader, Select, Textarea } from "../../../components/ui";
import { getPendingBills } from "../../../services/reception.service";
import { paymentModeLabel, paymentLabel, rupee } from "../utils";
import type { PaymentMode, PaymentStatus } from "../types";

export default function BillingShortcut() {
  const [mode, setMode] = useState<PaymentMode>("upi");
  const [status, setStatus] = useState<PaymentStatus>("paid");
  const [amount, setAmount] = useState(800);
  const bills = getPendingBills();
  const total = useMemo(() => bills.reduce((sum, b) => sum + b.amount - b.discount, 0), [bills]);
  return <div className="space-y-5"><PageHeader title="Billing Shortcut" description="Reception-side quick billing for completed consultations. Full billing comes later." action={<Button icon={<ReceiptIndianRupee className="size-4" />}>Generate Receipt Preview</Button>} /><div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><Card className="p-5"><h2 className="font-bold">Pending bills</h2><Input className="mt-4" placeholder="Search patient" /><div className="mt-4 space-y-3">{bills.map((bill) => <button key={bill.id} onClick={() => setAmount(bill.amount - bill.discount)} className="w-full rounded-xl border p-4 text-left hover:border-brand-300 hover:bg-brand-50"><div className="flex justify-between"><b>{bill.patientName}</b><b>{rupee(bill.amount - bill.discount)}</b></div><p className="mt-1 text-sm text-slate-500">{bill.service} · {bill.doctorName} · {bill.completedAt}</p></button>)}</div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-700">Total pending today: {rupee(total)}</p></Card><Card className="p-5"><h2 className="font-bold">Quick bill card</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Input placeholder="Patient" defaultValue="Arjun Nair" /><Input placeholder="Service" defaultValue="Dental Checkup" /><Input type="number" value={amount} onChange={(e) => setAmount(Number(e.target.value))} /><Input type="number" placeholder="Discount" defaultValue={0} /><Select value={mode} onChange={(e) => setMode(e.target.value as PaymentMode)}>{Object.entries(paymentModeLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select><Select value={status} onChange={(e) => setStatus(e.target.value as PaymentStatus)}>{Object.entries(paymentLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select><Textarea className="md:col-span-2" placeholder="Notes" /></div><div className="mt-5 rounded-2xl border bg-slate-50 p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Receipt preview</p><div className="mt-3 flex justify-between"><span>Vernex Multispeciality Clinic</span><b>{rupee(amount)}</b></div><p className="mt-2 text-sm text-slate-500">Mode: {paymentModeLabel[mode]} · Status: {paymentLabel[status]}</p><Button className="mt-4 w-full">Generate Receipt Preview</Button></div></Card></div></div>;
}
