import { useMemo, useState } from "react";
import { Button, Card, Input, Modal, PageHeader, Select } from "../../../components/ui";
import { getPrescriptionQueue } from "../../../services/pharmacy.service";
import { PrescriptionQueueTable } from "../components/PrescriptionQueueTable";
import { StockStatusBadge } from "../components/StockStatusBadge";
import type { PaymentStatus, PrescriptionQueueItem, PrescriptionStatus } from "../types";

export default function PrescriptionQueue() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<PrescriptionStatus | "all">("all"); const [payment, setPayment] = useState<PaymentStatus | "all">("all"); const [selected, setSelected] = useState<PrescriptionQueueItem | null>(null);
  const rows = useMemo(() => getPrescriptionQueue().filter((rx) => (status === "all" || rx.status === status) && (payment === "all" || rx.paymentStatus === payment) && `${rx.token} ${rx.patientName} ${rx.doctorName}`.toLowerCase().includes(query.toLowerCase())), [query, status, payment]);
  return <div className="space-y-5"><PageHeader title="Prescription Queue" description="Bill and dispense prescriptions sent by doctors." /><Card className="p-4"><div className="grid gap-3 lg:grid-cols-5"><Input placeholder="Search prescription" value={query} onChange={(e) => setQuery(e.target.value)} /><Select><option>All doctors</option><option>Dr. Priya Sharma</option><option>Dr. Aisha Khan</option></Select><Select value={status} onChange={(e) => setStatus(e.target.value as PrescriptionStatus | "all")}><option value="all">All status</option><option value="pending">Pending</option><option value="billed">Billed</option><option value="partially_dispensed">Partially dispensed</option><option value="dispensed">Dispensed</option><option value="cancelled">Cancelled</option></Select><Input type="date" defaultValue="2026-07-01" /><Select value={payment} onChange={(e) => setPayment(e.target.value as PaymentStatus | "all")}><option value="all">All payment</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="partial">Partial</option></Select></div></Card><Card className="p-5"><PrescriptionQueueTable items={rows} onView={setSelected} /></Card><Modal open={!!selected} onClose={() => setSelected(null)} title="Prescription detail">{selected && <div className="space-y-4"><div><b>{selected.patientName}</b><p className="text-sm text-slate-500">{selected.doctorName} · {selected.diagnosis}</p></div>{selected.medicines.map((m) => <div key={m.medicineName} className="rounded-xl border p-3"><div className="flex justify-between"><b>{m.medicineName}</b><StockStatusBadge status={m.availability} /></div><p className="mt-1 text-sm text-slate-500">{m.dosage} · {m.frequency} · {m.timing} · {m.duration}</p><p className="text-xs text-slate-400">{m.instructions || "Substitute Needed placeholder if unavailable"}</p></div>)}<div className="flex flex-wrap gap-2"><Button>Create bill</Button><Button variant="secondary">Send bill to WhatsApp</Button><Button variant="secondary">Print</Button></div></div>}</Modal></div>;
}
