import { useEffect, useState } from "react";
import { Button, Input, Modal, Select, Textarea } from "../../../components/ui";
import type { WhatsAppTemplate } from "../types";

export function TemplateEditorModal({ template, onClose, onSave, saving = false }: { template: WhatsAppTemplate | null; onClose: () => void; onSave?: (template: WhatsAppTemplate) => void; saving?: boolean }) {
  const [draft, setDraft] = useState<WhatsAppTemplate | null>(template);
  useEffect(() => setDraft(template), [template]);
  return <Modal open={!!template} onClose={onClose} title="Template Editor">{draft && <div className="max-h-[72vh] space-y-4 overflow-y-auto pr-1"><Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Template name" /><Select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value as WhatsAppTemplate["category"] })}><option value="booking">Booking</option><option value="reminder">Reminder</option><option value="payment">Payment</option><option value="follow_up">Follow-up</option><option value="review">Review</option><option value="cancellation">Cancellation</option></Select><Textarea rows={6} value={draft.previewText} onChange={(event) => setDraft({ ...draft, previewText: event.target.value })} placeholder="Message body" /><Input value={draft.variables.join(", ")} onChange={(event) => setDraft({ ...draft, variables: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} placeholder="Variables" /><Select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as WhatsAppTemplate["status"] })}><option value="active">Active</option><option value="draft">Draft</option><option value="needs_api_approval">Needs API approval</option><option value="disabled">Disabled</option></Select><p className="rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-700">Final WhatsApp template approval will be handled after official WhatsApp API integration.</p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button loading={saving} onClick={() => onSave?.(draft)}>Save template</Button></div></div>}</Modal>;
}
